language: c

matrix:
  include:
    - os: linux
      compiler: clang
      env: EXTRA_FLAGS="-DCLANG_ADDRESS_SANITIZER=ON"
    - os: linux
      compiler: gcc-5
      env: GCOV=gcov-5 CMAKE_FLAGS="-DUSE_COVERAGE=ON"

before_install:
  # cmocka
  - wget https://cmocka.org/files/1.1/cmocka-1.1.3.tar.xz
  - tar -xJvf cmocka-1.1.3.tar.xz
  - cd cmocka-1.1.3 && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..
  - rm -rf cmocka-1.1.3
  - .ci/before_install.sh

install: .ci/install.sh

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - build-essential
      - clang-3.4
      - cmake
      - g++-5-multilib
      - g++-multilib
      - gcc-5-multilib
      - gcc-multilib
      - gdb
      - libc6-dev-i386
      - libtool
      - llvm-3.4-dev
      - ninja-build
      - pkg-config
      - python3.3-dev
      - libbsd-dev
      - libhiredis-dev

before_script: redis-server redis-test.conf
script: make sb && make test && make sb-makekey && ./build/bin/sb-makekey && ./build/bin/sb-test
after_success: .ci/after_success.sh
